# Generated by Django 3.1.6 on 2021-02-10 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer_body', models.CharField(max_length=248)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1024)),
                ('variants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.answervariant')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_body', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_private', models.BooleanField(default=False)),
                ('code', models.CharField(db_index=True, max_length=8)),
                ('title', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('tags', models.ManyToManyField(db_index=True, null=True, to='api.Tag')),
            ],
        ),
    ]
