# Generated by Django 3.1.6 on 2021-02-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210211_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervariant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
